import type { CaptionPreset } from '../../types/caption';

export const BUILT_IN_PRESETS: CaptionPreset[] = [
  {
    id: 'classic',
    name: 'Classic',
    isBuiltIn: true,
    style: {
      fontFamily: 'Arial',
      fontSize: 48,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      textColor: '#FFFFFFFF',
      outlineColor: '#000000FF',
      outlineWidth: 2,
      shadowColor: '#00000080',
      shadowOffsetX: 0,
      shadowOffsetY: 2,
      shadowBlur: 4,
      backgroundColor: '#00000000',
      backgroundPadding: 16,
      backgroundBorderRadius: 8,
      backgroundOpacity: 1,
      verticalPosition: 'bottom',
      horizontalPosition: 'center',
      marginBottom: 60,
      marginTop: 60,
      animation: { type: 'fade', duration: 200 },
    },
  },
  {
    id: 'netflix',
    name: 'Netflix',
    isBuiltIn: true,
    style: {
      fontFamily: 'Arial',
      fontSize: 52,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      textColor: '#FFFFFFFF',
      outlineColor: '#000000FF',
      outlineWidth: 3,
      shadowColor: '#00000000',
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      shadowBlur: 0,
      backgroundColor: '#000000CC',
      backgroundPadding: 12,
      backgroundBorderRadius: 0,
      backgroundOpacity: 1,
      verticalPosition: 'bottom',
      horizontalPosition: 'center',
      marginBottom: 50,
      marginTop: 50,
      animation: { type: 'none', duration: 0 },
    },
  },
  {
    id: 'youtube',
    name: 'YouTube',
    isBuiltIn: true,
    style: {
      fontFamily: 'Roboto',
      fontSize: 44,
      fontWeight: 600,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      textColor: '#FFFFFFFF',
      outlineColor: '#000000FF',
      outlineWidth: 2,
      shadowColor: '#000000AA',
      shadowOffsetX: 2,
      shadowOffsetY: 2,
      shadowBlur: 3,
      backgroundColor: '#00000099',
      backgroundPadding: 8,
      backgroundBorderRadius: 4,
      backgroundOpacity: 1,
      verticalPosition: 'bottom',
      horizontalPosition: 'center',
      marginBottom: 40,
      marginTop: 40,
      animation: { type: 'fade', duration: 150 },
    },
  },
  {
    id: 'bold-impact',
    name: 'Bold Impact',
    isBuiltIn: true,
    style: {
      fontFamily: 'Impact',
      fontSize: 64,
      fontWeight: 900,
      fontStyle: 'normal',
      textTransform: 'uppercase',
      letterSpacing: 2,
      textColor: '#FFFF00FF',
      outlineColor: '#000000FF',
      outlineWidth: 4,
      shadowColor: '#000000CC',
      shadowOffsetX: 3,
      shadowOffsetY: 3,
      shadowBlur: 8,
      backgroundColor: '#00000000',
      backgroundPadding: 16,
      backgroundBorderRadius: 0,
      backgroundOpacity: 1,
      verticalPosition: 'center',
      horizontalPosition: 'center',
      marginBottom: 60,
      marginTop: 60,
      animation: { type: 'slide-up', duration: 300 },
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    isBuiltIn: true,
    style: {
      fontFamily: 'Helvetica',
      fontSize: 40,
      fontWeight: 400,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 0,
      textColor: '#FFFFFFFF',
      outlineColor: '#00000000',
      outlineWidth: 0,
      shadowColor: '#00000000',
      shadowOffsetX: 0,
      shadowOffsetY: 0,
      shadowBlur: 0,
      backgroundColor: '#000000DD',
      backgroundPadding: 16,
      backgroundBorderRadius: 8,
      backgroundOpacity: 1,
      verticalPosition: 'bottom',
      horizontalPosition: 'center',
      marginBottom: 40,
      marginTop: 40,
      animation: { type: 'fade', duration: 200 },
    },
  },
  {
    id: 'karaoke',
    name: 'Karaoke',
    isBuiltIn: true,
    style: {
      fontFamily: 'Arial',
      fontSize: 56,
      fontWeight: 700,
      fontStyle: 'normal',
      textTransform: 'none',
      letterSpacing: 1,
      textColor: '#00FFFFFF',
      outlineColor: '#000000FF',
      outlineWidth: 3,
      shadowColor: '#000000AA',
      shadowOffsetX: 2,
      shadowOffsetY: 2,
      shadowBlur: 4,
      backgroundColor: '#00000000',
      backgroundPadding: 16,
      backgroundBorderRadius: 0,
      backgroundOpacity: 1,
      verticalPosition: 'bottom',
      horizontalPosition: 'center',
      marginBottom: 80,
      marginTop: 80,
      animation: { type: 'word-highlight', duration: 300 },
    },
  },
];

export function loadUserPresets(): CaptionPreset[] {
  try {
    const stored = localStorage.getItem('caption-studio-presets');
    if (!stored) return [];
    return JSON.parse(stored);
  } catch {
    return [];
  }
}

export function saveUserPresets(presets: CaptionPreset[]) {
  try {
    localStorage.setItem('caption-studio-presets', JSON.stringify(presets));
  } catch (error) {
    console.error('Failed to save presets:', error);
  }
}
